steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/girisha-daggula-100974333/girisha100974333/app:v1.0', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/girisha-daggula-100974333/girisha100974333/app:v1.0']

options:
  logging: CLOUD_LOGGING_ONLY


