steps:
  # Step 1: Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/daggula/girisha-100974333/app:$COMMIT_SHA",
        ".",
      ]

  # Step 2: Push the Docker image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/daggula/girisha-100974333/app:$COMMIT_SHA",
      ]

  # Step 3: Deploy the image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "my-nodejs-app",
        "--image",
        "us-central1-docker.pkg.dev/daggula/girisha-100974333/app:$COMMIT_SHA",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--timeout",
        "600",
     ]
options:
  logging: CLOUD_LOGGING_ONLY
